### ISSUE TITLE
[OpenStack] UserData is not working when submitting a new Compute

### ISSUE THREAD

**Issue by arn3tt** [fogbow/resource-allocation-service#217]

**Comment by pauloewerton** [comment]
i guess we can close this already, right? @arn3tt @fubica

**Comment by fubica** [comment]
I haven't tested, but I think it has already been corrected.

**Comment by pauloewerton** [comment]
@fubica IMO this not something that needs to be fixed, we were just not passing the required shebang line in our userdata scripts. please refer to this sample userdata from the openstack official documentation: https://wiki.openstack.org/wiki/Userdata-examples

**Comment by fubica** [comment]
Agreed!
