### ISSUE TITLE
[OpenNebula] CreateCompute is returning no available resource

### ISSUE THREAD

**Issue by wassoares** [fogbow/resource-allocation-service#224]

**Comment by wassoares** [comment]
NOTE:
- During the choice of flavor from the valid templates the following error message occurs:
[one.vm.allocate] DISK 1: SIZE attribute must be a positive integer value.

SOLUTION:
- Get the disk size in the corresponding image ID template;

TODO: 
- Fix implementation of loadImageSizeDisk and updateHardwareRequirements methods;

**Comment by wassoares** [comment]
The PR (pull request) #230 of the project fogbow/resource-allocation-service and PR #9 of the project fogbow/common fixes this issue.

**Comment by pauloewerton** [comment]
@wassoares can we close this issue? PR #230 has already been merged.

**Comment by wassoares** [comment]
Yes.
