### ISSUE TITLE
[Cloudstack] Security rules are not working

### ISSUE THREAD

**Issue by fubica** [fogbow/resource-allocation-service#226]

**Comment by pauloewerton** [comment]
@fubica please notice we support this feature in public ip orders only. i've recently tested this and it seemed to work just fine. can you please give more details?

**Comment by fubica** [comment]
I see. The problem was when adding a security rule to a network, that I now understand is not supported in CloudStack. We need to create a new exception for unsupported operations, so that a client can distinguish between this case and the other possible source of failures.

**Comment by fgan1** [comment]
I was Fixed.
