### ISSUE TITLE
[Cloudstack] Unable to ssh to a VM to which a public IP was assigned. It seems to connect, ask for a password, but fails authentication (see screenshot attached).

### ISSUE THREAD

**Issue by fubica** [fogbow/resource-allocation-service#228]
![Screen Shot 2019-03-20 at 16 36 03 ](https://user-images.githubusercontent.com/7047759/54713824-4e8db780-4b2e-11e9-8ec1-c46874f43f48.png)

**Comment by pauloewerton** [comment]
i was able to reproduce this bug even using a cloudinit enabled image. requires further investigation.

**Comment by fgan1** [comment]
I was fixed
