### ISSUE TITLE
[OpenStack] Get Public IP order security rules returns null CIDR on all rules

### ISSUE THREAD

**Issue by pauloewerton** [fogbow/resource-allocation-service#229]

**Comment by fubica** [comment]
In fact, it should have four rules, as follows:

Direction | Ether Type | IP Protocol | Port Range | CIDR
Egress       IPv4              Any              Any               0.0.0.0/0
Egress       IPv6              Any              Any               ::/0
Ingress      IPv4              TCP             22                 0.0.0.0/0
Ingress      IPv6              TCP             22                 ::/0

**Comment by pauloewerton** [comment]
@fubica thanks for the correction i will update the title. also, in my tests, the security rules listing from a public ip order from cloudstack returns only the ipv4 tcp 22 rule.

**Comment by fubica** [comment]
Here the most important thing is to guarantee a common semantics for Fogbow, independent from the underlying cloud. The idea is that when a public IP is attached to a compute, then port 22 is open to anyone willing to connect to the VM (how this is implemented by the underlying cloud can vary).

**Comment by pauloewerton** [comment]
we probably should be using "remote_ip_prefix" as the key to get cidr in our json response object. refer to: https://developer.openstack.org/api-ref/network/v2/index.html?expanded=list-floating-ips-detail,show-security-group-rule-detail#show-security-group-rule

**Comment by fubica** [comment]
I believe that CIDR is the correct way to call this field (see https://pt.wikipedia.org/wiki/Classless_Inter-Domain_Routing). I think OpenStack folks got that one wrong. See for example AWS syntax (https://medium.com/@dbclin/a-bash-script-to-update-an-existing-aws-security-group-with-my-new-public-ip-address-d0c965d67f28).

**Comment by pauloewerton** [comment]
@fubica yes, i misread our code. we're already using gson to map "remote_ip_prefix" to cidr in our json response object. please, ignore my previous comment.

**Comment by pauloewerton** [comment]
we're not specifically passing a cidr (remote ip prefix) when creating a public ip default security rules. please check: https://github.com/fogbow/resource-allocation-service/blob/develop/src/main/java/cloud/fogbow/ras/core/plugins/interoperability/openstack/publicip/v2/OpenStackPublicIpPlugin.java#L217. in the openstack api, that parameter is optional so it will return null on get operation, meaning "allow to all". 

we can create a filter on the clients, such as the GUI, to present that data differently. horizon values for this case are "-" (ingress), "0.0.0.0/0" and "::/0" (egress).

**Comment by fubica** [comment]
I think it is fine to adopt OpenStack's syntax and semantic. I would only check whether this is consistent with other cloud orchestrators/providers (eg. CloudStack, AWS, etc.).

**Comment by pauloewerton** [comment]
@fubica we know by now that in cloudstack, for instance, there are restrictions for creating certain types of rules. so, to implement consistency across clouds for getting security rules could be in the fogbow to do list.

**Comment by fubica** [comment]
Fine.

**Comment by wassoares** [comment]
Fixed with the pull request #477.
