### ISSUE TITLE
Cloudstack plugin throws a generic exception

### ISSUE THREAD

**Issue by fgan1** [fogbow/resource-allocation-service#451]
To every error 431, the Cloudstack plugin throws a generic exception. It makes hard to understand the real problem due to this fact.
We must improve it. First of all, it is necessary to understand the reason.

![image](https://user-images.githubusercontent.com/793219/81971474-863fa480-95f7-11ea-9870-8299acd13824.png)

**Comment by wassoares** [comment]
Fixed with the branch **fix-cloudstack-http-request-client** in the **common** project.
